products:
  - title: Sample Product 1
    image: images/product-sample.png
    description: Information about product 1.
  - title: Sample Product 2
    image: images/product-sample.png
    description: Information about product 2.
  - title: Sample Product 3
    image: images/product-sample.png
    description: Information about product 3.
  - title: Sample Product 4
    image: images/product-sample.png
    description: Information about product 4.
